### ISSUE TITLE
Provide the repo in zuul and kebechet config. 

### ISSUE THREAD

**Issue by harshad16** [thoth-station/graph-backup-job#3]
**Is your feature request related to a problem? Please describe.**
To have package updates and auto merging of pr, the support of zuul and kebechet is needed.

**Describe the solution you'd like**
The repo information is needed to be added to zuul and kebechet config files, for them to assist this repo.

**Describe alternatives you've considered**
None, do everything manually I guess :thinking: 

**Additional context**
Required to look at kebechet and zuul-config repo.

**Comment by fridex** [comment]
Zuul seems to ignore this repo even though we have https://github.com/thoth-station/zuul-config/blob/master/zuul/graph-backup-job.yaml and .zuul.yaml in this repo. Do we need zuul restart to take effect? CC @goern 

Kebechet now operates on this repo so this part seems to be ok.

**Comment by fridex** [comment]
Also, webhooks do not trigger builds in test environment on merge to master.

**Comment by goern** [comment]
I'll have I look, I observed that behavior before but forgot to look at it over Xmas :(

**Comment by goern** [comment]
I added the repo manually to zuul's `main.yaml`, it shows up in Zuul's project list, lets see how it behaves...

**Comment by goern** [comment]
it seems to work, pls reopen if you see something suspicious
