### ISSUE TITLE
Builds failing in test environment - they cannot pull builder image

### ISSUE THREAD

**Issue by fridex** [thoth-station/graph-backup-job#77]
**Describe the bug**

Builds of graph-backup-job are failing in thoth-test-core - error in pulling base image from quay.

**To Reproduce**
1. Go to thoth-test-core
2. Click on builds
3. Scroll down to graph-backup-job

**Expected behavior**
Builds should succeed.

**Screenshots**

```

Cloning "https://github.com/thoth-station/graph-backup-job " ...
--
  | Commit:	c57e48fe1de06fce11ea8430ab537cf0374ea2c5 (Merge pull request #74 from thoth-station/adding-managers-patch-1)
  | Author:	thoth-zuul[bot] <40421472+thoth-zuul[bot]@users.noreply.github.com>
  | Date:	Tue Feb 11 06:50:08 2020 +0000
  | pulling image error : manifest for quay.io/thoth-station/s2i-thoth-ubi8-py36-postgres@sha256:0e28ac29fcab9a82d8d9daadb6c03a2f36b881722ec10a8fe780bc8be7ee1717 not found
  | error: build error: unable to get quay.io/thoth-station/s2i-thoth-ubi8-py36-postgres@sha256:0e28ac29fcab9a82d8d9daadb6c03a2f36b881722ec10a8fe780bc8be7ee1717

```

**Comment by harshad16** [comment]
This could be because the image in quay has been updated and the image with this sha `sha256:0e28ac29fcab9a82d8d9daadb6c03a2f36b881722ec10a8fe780bc8be7ee1717` doesn't exist anymore. I will update the image in test namespace, let's observe and see if this is actually the issue.

**Comment by harshad16** [comment]
After the import of the latest image, the build has completed 
https://paas.psi.redhat.com/console/project/thoth-test-core/browse/pods/graph-backup-job-56-build?tab=details

let me know if you think if there is a much bigger issue here :smile:?

**Comment by fridex** [comment]
> After the import of the latest image, the build has completed
> https://paas.psi.redhat.com/console/project/thoth-test-core/browse/pods/graph-backup-job-56-build?tab=details
> 
> let me know if you think if there is a much bigger issue here ?

Awesome, thanks! :muscle:
